apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow

on:
  workflow_dispatch: 
    inputs:
      manifest:
        type: string
        required: true
      

jobs:
  app1:
    if: ${{ fromJSON(inputs.manifest)['preprod-python-helloworld'].deploy }}
    uses: cbp-test-preprod/preprod-python-helloworld/.cloudbees/workflows/deploy.yaml
    with:
      manifest: ${{ toJSON(fromJSON(inputs.manifest)['preprod-python-helloworld']) }}
      environment: PREPROD
